### ISSUE TITLE
feat: 눈 깜빡임 인식 -> 타겟 자동 생성 -> 타겟 제거 함수 구현 -> 조건 달성 시 게임 종료

### ISSUE THREAD

**Issue by LeeSungNo-ian** [LeeSungNo-ian/EyeTracking-ARKit#5]
## 🎯 이슈 개요
| 이슈 내용 | 눈 깜빡임 인식 -> 타겟 자동 생성 -> 타겟 제거 함수 구현 -> 조건 달성 시 게임 종료 |
| --- | --- |
| 마감 일자 | 2022.08 |

## 🏹 Todo
 - [x] 타겟을 자동으로 생성합니다.
 - [x] 눈 깜빡임을 인식합니다.
 - [x] 눈 깜빡임을 인식해 타겟을 제거합니다. 
 - [x] 조건을 달성하면 게임이 종료됩니다.
