### ISSUE TITLE
feat: MainPage UI 구현 -> Design Asset 변경

### ISSUE THREAD

**Issue by LeeSungNo-ian** [LeeSungNo-ian/EyeTracking-ARKit#7]
## 🎯 이슈 개요
| 이슈 내용 | MainPage UI 구현 -> Design Asset 변경 |
| --- | --- |
| 마감 일자 | 2022.09.02 |

## 🏹 Todo
 - [x] MainPage UI를 구현합니다.
 - [x] 눈동자가 움직이는 애니메이션을 구현합니다.
 - [x] GamePage 디자인을 재구성합니다.
